# Default values for fxce-colosseum.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appVersion: 0.1.1
name: fxce-cls-api
replicaCount: 1

image:
  repository: git.vncdevs.io:5005/fxce/fxce-colosseum
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: develop
tcpPort: 3001
port: 3000

imagePullSecrets:
  - name: vncdevs-io

nameOverride: ""
fullnameOverride: ""

securityContext:
  allowPrivilegeEscalation: false
  capabilities: {}
  privileged: false
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  stdin: true
  terminationMessagePath: /dev/termination-log
  terminationMessagePolicy: File
  tty: true
dnsPolicy: ClusterFirst

# args:
#   - bundle install; ATTACHED_API=1 ATTACHED_SIDEKIQ=1 rails s
# command:
#   - /bin/bash
#   - -c
# env:
# - name: ATTACHED_API
#   value: "1"
# - name: LOG_LEVEL
#   value: debug
envFrom:
- secretRef:
    name: fxce-colosseum-secret
    optional: false
- configMapRef:
    name: fxce-colosseum-env
    optional: false
restartPolicy: Always
schedulerName: default-scheduler
initSSL:
  enabled: true

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

kuberesolver:
  enabled: false

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false
  capabilities: {}
  privileged: false

service:
  name: fxce-cls-api
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# nginxSidecar:
#   enabled: true
#   service:
#     http: 80
#     https: 443
#   image:
#     repository: nginx
#     tag:  stable
#     pullPolicy: IfNotPresent
#   upstream:
#     host: 127.0.0.1
#     port: 3000
#   tls:
#   # location of files
#     secret: nginx-sidecar-tls
#     crt: /etc/nginx/ssl/tls.crt
#     key: /etc/nginx/ssl/tls.key
#   configmapName: nginx-sidecard-configmap
